version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: instilldb
      POSTGRES_USER: instilluser
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: