# Generated by Django 4.1.7 on 2023-03-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=155, null=True)),
                ('user_id', models.PositiveIntegerField()),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['title'],
            },
        ),
    ]
